name: DSPipeline

on:
  push:
    branches: [ main ]

jobs:
  DockerBuildPublish:
    runs-on: ubuntu-latest

    steps:
    - name: Télécharger le code
      uses: actions/checkout@v3

    - name: Connexion à GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Construire l’image Docker
      run: |
        docker build -t ghcr.io/cheikhmalainine1973/mydsapp:latest .

    - name: Envoyer l’image sur GitHub Container Registry
      run: |
        docker push ghcr.io/cheikhmalainine1973/mydsapp:latest

